### ISSUE TITLE
Refactor autocomplete

### ISSUE THREAD

**Issue by riccardocescon** [alexrintt/lichess.dart#19]
Should we switch the 'autocomplete' api's name with 'getUsersByTerm'?

**Comment by alexrintt** [comment]
what do you think `searchByTerm`?

users is duplicating the context:

```dart
usersService.getUsersByTerm(...)
```

**Comment by riccardocescon** [comment]
Yeah that's pretty good, but what for the autocompleteUsernames?
autocompelte --> List<User>
autompleteUsernames --> List<String>

**Comment by alexrintt** [comment]
nice question, tbh idk, maybe `getUsernameSuggestions` maybe?

```dart
usersService.getUsernameSuggestions(term: 'ricc');
```

**Comment by riccardocescon** [comment]
What about
`usersService.searchByTerm(...)` and `usersService.searchNamesByTerm(...)`?

**Comment by alexrintt** [comment]
seems pretty good, gotta update to this then.

autocomplete -> searchByTerm.
autocompleteUsernames -> searchNamesByTerm.
